In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('../artifacts/Job_Data.csv')

In [3]:
data.shape

(10000, 22)

## Data Preprocessing

In [4]:
data.duplicated().sum()

np.int64(0)

In [5]:
data.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Degree_Program                  0
Academic_Performance            0
Certifications_Count            0
Internship_Experience           0
Skill_Programming               0
Skill_Database_SQL              0
Skill_Version_Control_Git       0
Skill_Problem_Solving           0
Skill_Communication             0
Job_ID                          0
Job_Title                       0
Required_Programming            0
Required_Database_SQL           0
Required_Version_Control_Git    0
Required_Problem_Solving        0
Required_Communication          0
Min_Experience_Months           0
Location                        0
Job_Match                       0
dtype: int64

In [6]:
data['Job_Title'].value_counts()

Job_Title
Data Analyst            1590
Security Analyst        1442
QA Engineer             1380
Frontend Developer      1321
ML Engineer             1318
DevOps Engineer         1298
Mobile App Developer     874
AI Engineer              777
Name: count, dtype: int64

In [7]:
data['Degree_Program'].value_counts()

Degree_Program
Computer Science and Engineering    1864
AI Engineering                      1810
Software Engineering                1802
Information Technology              1715
Data Science                        1468
Cybersecurity                       1341
Name: count, dtype: int64

In [8]:
data['Location'].value_counts()

Location
Delhi        1738
Chennai      1680
Pune         1664
Mumbai       1647
Kolkata      1640
Bangalore    1631
Name: count, dtype: int64

In [9]:
data= data.drop(columns=['Gender','Student_ID','Job_ID','Location','Age'])

In [10]:
data = pd.get_dummies(data,columns=['Job_Title','Degree_Program'])
feature_columns = data.drop('Job_Match',axis=1).columns.tolist()

In [11]:
data.shape

(10000, 29)

In [12]:
data.head(2)

,Academic_Performance,Certifications_Count,Internship_Experience,Skill_Programming,Skill_Database_SQL,Skill_Version_Control_Git,Skill_Problem_Solving,Skill_Communication,Required_Programming,Required_Database_SQL,...,Job_Title_ML Engineer,Job_Title_Mobile App Developer,Job_Title_QA Engineer,Job_Title_Security Analyst,Degree_Program_AI Engineering,Degree_Program_Computer Science and Engineering,Degree_Program_Cybersecurity,Degree_Program_Data Science,Degree_Program_Information Technology,Degree_Program_Software Engineering
0,51.38,2,8,8,2,5,7,6,7,7,...,False,False,False,False,False,True,False,False,False,False
1,67.83,2,0,5,1,6,7,0,10,7,...,False,False,False,False,False,False,True,False,False,False

In [13]:
data.shape

(10000, 29)

In [14]:
data.head(2)

,Academic_Performance,Certifications_Count,Internship_Experience,Skill_Programming,Skill_Database_SQL,Skill_Version_Control_Git,Skill_Problem_Solving,Skill_Communication,Required_Programming,Required_Database_SQL,...,Job_Title_ML Engineer,Job_Title_Mobile App Developer,Job_Title_QA Engineer,Job_Title_Security Analyst,Degree_Program_AI Engineering,Degree_Program_Computer Science and Engineering,Degree_Program_Cybersecurity,Degree_Program_Data Science,Degree_Program_Information Technology,Degree_Program_Software Engineering
0,51.38,2,8,8,2,5,7,6,7,7,...,False,False,False,False,False,True,False,False,False,False
1,67.83,2,0,5,1,6,7,0,10,7,...,False,False,False,False,False,False,True,False,False,False

In [15]:
data.shape

(10000, 29)

In [16]:
data.head(2)

,Academic_Performance,Certifications_Count,Internship_Experience,Skill_Programming,Skill_Database_SQL,Skill_Version_Control_Git,Skill_Problem_Solving,Skill_Communication,Required_Programming,Required_Database_SQL,...,Job_Title_ML Engineer,Job_Title_Mobile App Developer,Job_Title_QA Engineer,Job_Title_Security Analyst,Degree_Program_AI Engineering,Degree_Program_Computer Science and Engineering,Degree_Program_Cybersecurity,Degree_Program_Data Science,Degree_Program_Information Technology,Degree_Program_Software Engineering
0,51.38,2,8,8,2,5,7,6,7,7,...,False,False,False,False,False,True,False,False,False,False
1,67.83,2,0,5,1,6,7,0,10,7,...,False,False,False,False,False,False,True,False,False,False

In [17]:
data.corr()

,Academic_Performance,Certifications_Count,Internship_Experience,Skill_Programming,Skill_Database_SQL,Skill_Version_Control_Git,Skill_Problem_Solving,Skill_Communication,Required_Programming,Required_Database_SQL,...,Job_Title_ML Engineer,Job_Title_Mobile App Developer,Job_Title_QA Engineer,Job_Title_Security Analyst,Degree_Program_AI Engineering,Degree_Program_Computer Science and Engineering,Degree_Program_Cybersecurity,Degree_Program_Data Science,Degree_Program_Information Technology,Degree_Program_Software Engineering
Academic_Performance,1.000000,-0.010745,-0.011223,0.010461,0.004127,-0.003066,-0.002547,0.004024,0.011210,-0.008255,...,0.010405,0.003947,-0.006086,0.012313,0.006569,0.017494,-0.013879,-0.004649,-0.003769,-0.004024
Certifications_Count,-0.010745,1.000000,0.001999,-0.001355,-0.010882,0.008036,-0.002028,-0.011421,-0.003314,-0.000465,...,-0.004272,0.002732,0.001693,0.010784,-0.013313,-0.001264,0.015003,0.007211,0.002506,-0.007783
Internship_Experience,-0.011223,0.001999,1.000000,0.064647,0.067720,0.059484,0.050840,0.075886,0.009497,-0.008845,...,0.014325,-0.001080,-0.011630,0.000992,0.008465,0.010598,-0.030573,-0.024393,0.029466,0.001451
Skill_Programming,0.010461,-0.001355,0.064647,1.000000,0.037410,0.033567,0.028329,0.036669,0.006357,0.009386,...,0.004892,-0.006566,-0.004998,-0.001024,0.013089,0.019957,-0.038259,-0.034086,0.018897,0.013442
Skill_Database_SQL,0.004127,-0.010882,0.067720,0.037410,1.000000,0.019928,0.025194,0.019975,-0.003488,0.014959,...,0.006857,-0.003598,0.012022,-0.004447,0.026752,0.007151,-0.027579,-0.020102,0.020276,-0.010967
Skill_Version_Control_Git,-0.003066,0.008036,0.059484,0.033567,0.019928,1.000000,0.029946,0.030567,-0.004648,-0.005121,...,-0.017315,-0.009501,0.001742,-0.010779,-0.001486,0.014998,-0.032254,-0.007214,0.011200,0.010547
Skill_Problem_Solving,-0.002547,-0.002028,0.050840,0.028329,0.025194,0.029946,1.000000,0.030160,-0.015522,0.001992,...,-0.011904,-0.010908,0.014170,0.002704,0.012835,0.003687,-0.040726,-0.021920,0.010566,0.029335
Skill_Communication,0.004024,-0.011421,0.075886,0.036669,0.019975,0.030567,0.030160,1.000000,-0.023180,0.007279,...,0.005932,-0.010124,0.006781,0.016275,0.010745,0.008682,-0.037091,-0.011470,0.017714,0.006513
Required_Programming,0.011210,-0.003314,0.009497,0.006357,-0.003488,-0.004648,-0.015522,-0.023180,1.000000,-0.471396,...,0.339765,0.273655,-0.345386,-0.162668,-0.014440,-0.006565,0.008959,-0.011005,0.002380,0.020973
Required_Database_SQL,-0.008255,-0.000465,-0.008845,0.009386,0.014959,-0.005121,0.001992,0.007279,-0.471396,1.000000,...,-0.041290,-0.170580,-0.046230,-0.057858,0.000300,0.000430,-0.009181,0.027167,-0.014083,-0.003799
Required_Version_Control_Git,-0.013330,-0.004245,-0.013204,0.007221,-0.014833,0.015704,-0.008323,-0.024295,0.262620,-0.401899,...,-0.177936,0.160273,0.041442,-0.386020,0.010428,0.011493,-0.023934,-0.015541,0.008191,0.005404
Required_Problem_Solving,0.000084,-0.005238,-0.008104,-0.000189,0.019169,-0.018150,0.008414,0.000286,-0.046423,-0.083561,...,0.245489,-0.146268,0.269451,0.254525,-0.006361,-0.016581,0.024565,0.011851,-0.005618,-0.004010
Required_Communication,0.005881,-0.003873,-0.006151,-0.001937,-0.001651,0.000967,0.008703,0.025994,-0.328685,0.222134,...,-0.418243,-0.169653,0.278562,0.044614,-0.000951,0.007099,0.015156,-0.007206,-0.005390,-0.007755
Min_Experience_Months,-0.008440,-0.008317,0.036678,-0.007443,-0.016103,-0.008448,-0.029653,-0.025147,0.147466,-0.180183,...,0.247802,-0.172250,-0.246867,0.261067,-0.010164,-0.008601,0.021521,0.012345,-0.022309,0.010328
Job_Match,0.014101,0.017608,0.371199,0.288948,0.267218,0.253807,0.318331,0.281655,-0.057749,0.036187,...,-0.018321,-0.001700,0.005062,0.003976,0.077081,0.078898,-0.206397,-0.119867,0.068601,0.068925
Job_Title_AI Engineer,-0.002505,-0.016356,0.019725,0.006652,0.005078,0.017284,0.010944,-0.012120,0.252316,-0.167681,...,-0.113089,-0.089823,-0.116134,-0.119144,-0.011291,-0.006554,0.000882,0.007321,-0.000253,0.010676
Job_Title_Data Analyst,-0.005075,0.007000,-0.011765,0.000823,0.015650,0.004511,0.001128,0.009373,-0.526655,0.778168,...,-0.169414,-0.134560,-0.173975,-0.178483,-0.002692,0.000438,-0.009806,0.038317,-0.015732,-0.008906
Job_Title_DevOps Engineer,-0.006544,0.001785,-0.007824,-0.001283,-0.021405,0.012699,-0.009009,-0.025358,-0.015661,-0.210325,...,-0.150479,-0.119521,-0.154530,-0.158535,0.009322,0.000040,-0.009659,-0.005504,-0.000479,0.004723
Job_Title_Frontend Developer,-0.006304,-0.007326,0.002283,0.001868,-0.011153,0.003490,0.002823,0.003356,0.337722,-0.208419,...,-0.152007,-0.120735,-0.156100,-0.160145,-0.000077,-0.008520,-0.008794,-0.013288,0.005836,0.023018
Job_Title_ML Engineer,0.010405,-0.004272,0.014325,0.004892,0.006857,-0.017315,-0.011904,0.005932,0.339765,-0.041290,...,1.000000,-0.120577,-0.155896,-0.159935,-0.015785,0.005560,-0.002380,0.021315,-0.002382,-0.005002
Job_Title_Mobile App Developer,0.003947,0.002732,-0.001080,-0.006566,-0.003598,-0.009501,-0.010908,-0.010124,0.273655,-0.170580,...,-0.120577,1.000000,-0.123823,-0.127032,0.012697,0.004625,-0.007485,-0.026316,0.009496,0.004150
Job_Title_QA Engineer,-0.006086,0.001693,-0.011630,-0.004998,0.012022,0.001742,0.014170,0.006781,-0.345386,-0.046230,...,-0.155896,-0.123823,1.000000,-0.164241,0.018239,0.013973,-0.011111,-0.019321,0.010253,-0.014843
Job_Title_Security Analyst,0.012313,0.010784,0.000992,-0.001024,-0.004447,-0.010779,0.002704,0.016275,-0.162668,-0.057858,...,-0.159935,-0.127032,-0.164241,1.000000,-0.010352,-0.010079,0.046470,-0.007791,-0.004005,-0.009516
Degree_Program_AI Engineering,0.006569,-0.013313,0.008465,0.013089,0.026752,-0.001486,0.012835,0.010745,-0.014440,0.000300,...,-0.015785,0.012697,0.018239,-0.010352,1.000000,-0.225017,-0.185003,-0.195000,-0.213886,-0.220405
Degree_Program_Computer Science and Engineering,0.017494,-0.001264,0.010598,0.019957,0.007151,0.014998,0.003687,0.008682,-0.006565,0.000430,...,0.005560,0.004625,0.013973,-0.010079,-0.225017,1.000000,-0.188364,-0.198543,-0.217773,-0.224409
Degree_Program_Cybersecurity,-0.013879,0.015003,-0.030573,-0.038259,-0.027579,-0.032254,-0.040726,-0.037091,0.008959,-0.009181,...,-0.002380,-0.007485,-0.011111,0.046470,-0.185003,-0.188364,1.000000,-0.163237,-0.179047,-0.184503
Degree_Program_Data Science,-0.004649,0.007211,-0.024393,-0.034086,-0.020102,-0.007214,-0.021920,-0.011470,-0.011005,0.027167,...,0.021315,-0.026316,-0.019321,-0.007791,-0.195000,-0.198543,-0.163237,1.000000,-0.188722,-0.194474
Degree_Program_Information Technology,-0.003769,0.002506,0.029466,0.018897,0.020276,0.011200,0.010566,0.017714,0.002380,-0.014083,...,-0.002382,0.009496,0.010253,-0.004005,-0.213886,-0.217773,-0.179047,-0.188722,1.000000,-0.213309
Degree_Program_Software Engineering,-0.004024,-0.007783,0.001451,0.013442,-0.010967,0.010547,0.029335,0.006513,0.020973,-0.003799,...,-0.005002,0.004150,-0.014843,-0.009516,-0.220405,-0.224409,-0.184503,-0.194474,-0.213309,1.000000

In [18]:
corr = data.corr(numeric_only=True)['Job_Match'].abs()
corr.sort_values()

Job_Title_Mobile App Developer                     0.001700
Job_Title_Frontend Developer                       0.001740
Job_Title_Security Analyst                         0.003976
Job_Title_QA Engineer                              0.005062
Job_Title_AI Engineer                              0.006603
Required_Communication                             0.008731
Academic_Performance                               0.014101
Certifications_Count                               0.017608
Job_Title_ML Engineer                              0.018321
Required_Problem_Solving                           0.027043
Required_Database_SQL                              0.036187
Job_Title_DevOps Engineer                          0.043113
Required_Version_Control_Git                       0.043373
Job_Title_Data Analyst                             0.052514
Required_Programming                               0.057749
Degree_Program_Information Technology              0.068601
Degree_Program_Software Engineering                0.068925
Degree_Program_AI Engineering                      0.077081
Degree_Program_Computer Science and Engineering    0.078898
Min_Experience_Months                              0.086741
Degree_Program_Data Science                        0.119867
Degree_Program_Cybersecurity                       0.206397
Skill_Version_Control_Git                          0.253807
Skill_Database_SQL                                 0.267218
Skill_Communication                                0.281655
Skill_Programming                                  0.288948
Skill_Problem_Solving                              0.318331
Internship_Experience                              0.371199
Job_Match                                          1.000000
Name: Job_Match, dtype: float64

In [19]:
data['Job_Match'].value_counts()

Job_Match
0    7000
1    3000
Name: count, dtype: int64

In [20]:
data['Job_Match'].value_counts(normalize=True)

Job_Match
0    0.7
1    0.3
Name: proportion, dtype: float64

## Building the model

In [21]:
x = data.drop('Job_Match',axis=1)
y = data['Job_Match']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, stratify=y, random_state=42
)

In [23]:
X_train.shape

(8000, 28)

In [24]:
X_test.shape

(2000, 28)

In [25]:
y_train.value_counts()

Job_Match
0    5600
1    2400
Name: count, dtype: int64

## Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(X_train)
x_test_scaled = scaler.fit_transform(X_test)

## Model Training and Evaluation

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [28]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def training_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act,y_pred),3)
    pr  = round(precision_score(y_act,y_pred),3)
    rec = round(recall_score(y_act,y_pred),3)
    f1  = round(f1_score(y_act,y_pred),3)
    print(f'Training Scores>\n\tAccuracy ={acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')

def validation_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act,y_pred),3)
    pr  = round(precision_score(y_act,y_pred),3)
    rec = round(recall_score(y_act,y_pred),3)
    f1  = round(f1_score(y_act,y_pred),3)
    print(f'Testing Scores>\n\tAccuracy ={acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('lr', LogisticRegression(max_iter=3000))
])

param_grid_lr = {
    'lr__C': [1, 10, 50, 100, 200, 500, 1000],
    'lr__class_weight': [None, 'balanced']
}

grid_search_lr = GridSearchCV(
    estimator=lr_pipeline,
    param_grid=param_grid_lr,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search_lr.fit(X_train, y_train)

print("Best parameters:", grid_search_lr.best_params_)
print("Best CV F1-score:", grid_search_lr.best_score_)

best_lr = grid_search_lr.best_estimator_

y_train_pred = best_lr.predict(X_train)
training_scores(y_train, y_train_pred)

y_test_pred = best_lr.predict(X_test)
validation_scores(y_test, y_test_pred)

Fitting 5 folds for each of 14 candidates, totalling 70 fits
Best parameters: {'lr__C': 1, 'lr__class_weight': 'balanced'}
Best CV F1-score: 0.8297383626185392
Training Scores>
	Accuracy =0.888
	Precision = 0.759
	Recall = 0.916
	F1-Score = 0.83
Testing Scores>
	Accuracy =0.903
	Precision = 0.795
	Recall = 0.912
	F1-Score = 0.849

In [29]:
mnb = MultinomialNB()
mnb.fit(X_train, y_train)

y_train_pred = mnb.predict(X_train)

training_scores(y_train,y_train_pred)

y_test_pred = mnb.predict(X_test)

validation_scores(y_test,y_test_pred)

Training Scores>
	Accuracy =0.864
	Precision = 0.761
	Recall = 0.795
	F1-Score = 0.777
Testing Scores>
	Accuracy =0.854
	Precision = 0.749
	Recall = 0.772
	F1-Score = 0.76

In [30]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [3,5,7,10,None],
    'min_samples_split': [2,5,10,20],
    'min_samples_leaf' : [1,2,5,10]
}

grid_search_dt = GridSearchCV(
    estimator = DecisionTreeClassifier(random_state=42),
    param_grid= param_grid,
    cv = 5,
    scoring = 'f1',
    n_jobs = -1
)

grid_search_dt.fit(X_train, y_train)

y_train_pred = grid_search_dt.predict(X_train)

training_scores(y_train,y_train_pred)

y_test_pred = grid_search_dt.predict(X_test)

validation_scores(y_test,y_test_pred)

Training Scores>
	Accuracy =0.964
	Precision = 0.93
	Recall = 0.95
	F1-Score = 0.94
Testing Scores>
	Accuracy =0.905
	Precision = 0.832
	Recall = 0.857
	F1-Score = 0.844

In [31]:

from sklearn.model_selection import GridSearchCV

param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5]
}

grid_search_rf = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid_rf,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

grid_search_rf.fit(X_train, y_train)

y_train_pred = grid_search_rf.predict(X_train)

training_scores(y_train,y_train_pred)

y_test_pred = grid_search_rf.predict(X_test)

validation_scores(y_test,y_test_pred)

Training Scores>
	Accuracy =1.0
	Precision = 1.0
	Recall = 1.0
	F1-Score = 1.0
Testing Scores>
	Accuracy =0.937
	Precision = 0.916
	Recall = 0.87
	F1-Score = 0.892

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


svm_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svc', SVC(kernel='rbf'))
])

param_grid_weighted = {
    'svc__C': [100, 500, 1000, 5000],
    'svc__gamma': [0.0001, 0.001, 0.01, 'scale'],
    'svc__class_weight': [None, 'balanced']
}


grid_search_svm = GridSearchCV(
    estimator=svm_pipeline,
    param_grid=param_grid_weighted,  # Use the new grid here
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search_svm.fit(X_train, y_train)

print("Best parameters:", grid_search_svm.best_params_)
print("Best CV F1-score:", grid_search_svm.best_score_)

y_train_pred = grid_search_svm.predict(X_train)
training_scores(y_train, y_train_pred)

y_test_pred = grid_search_svm.predict(X_test)
validation_scores(y_test, y_test_pred)

print(grid_search_svm.best_params_)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
Best parameters: {'svc__C': 5000, 'svc__class_weight': None, 'svc__gamma': 0.001}
Best CV F1-score: 0.9286597438796461
Training Scores>
	Accuracy =0.979
	Precision = 0.954
	Recall = 0.975
	F1-Score = 0.965
Testing Scores>
	Accuracy =0.959
	Precision = 0.915
	Recall = 0.952
	F1-Score = 0.933
{'svc__C': 5000, 'svc__class_weight': None, 'svc__gamma': 0.001}

## SVM Probability Calibration

In [31]:
from sklearn.calibration import CalibratedClassifierCV

calibrated_svm = CalibratedClassifierCV(
    estimator=grid_search_svm,
    method="sigmoid",
    cv=5
)

calibrated_svm.fit(X_train, y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits
Fitting 5 folds for each of 32 candidates, totalling 160 fits
Fitting 5 folds for each of 32 candidates, totalling 160 fits
Fitting 5 folds for each of 32 candidates, totalling 160 fits
Fitting 5 folds for each of 32 candidates, totalling 160 fits

CalibratedClassifierCV(cv=5,
                       estimator=GridSearchCV(cv=5,
                                              estimator=Pipeline(steps=[('scaler',
                                                                         StandardScaler()),
                                                                        ('svc',
                                                                         SVC())]),
                                              n_jobs=-1,
                                              param_grid={'svc__C': [100, 500,
                                                                     1000,
                                                                     5000],
                                                          'svc__class_weight': [None,
                                                                                'balanced'],
                                                          'svc__gamma': [0.0001,
                                                                         0.001,
                                                                         0.01,
                                                                         'scale']},
                                              scoring='f1', verbose=1))

In [32]:
import pickle

with open('../static/model/model.pickle', 'wb') as file:
    pickle.dump(calibrated_svm, file)

with open('../static/model/feature_columns.pickle', 'wb') as file:
    pickle.dump(feature_columns, file)

In [33]:
p = calibrated_svm.predict_proba(X_test)[:, 1]
print(np.histogram(p, bins=10, range=(0, 1))[0])
print(validation_scores(y_test, calibrated_svm.predict(X_test)))

[1233   44   42   34   29   34   36   51   68  429]
Testing Scores>
	Accuracy =0.957
	Precision = 0.916
	Recall = 0.943
	F1-Score = 0.929
None